@startuml
left to right direction
actor Aluno
actor Professor
actor EmpresaParceira

usecase "Cadastrar no Sistema" as CA1
usecase "Distribuir Moedas" as CA2
usecase "Consultar extrato" as CA3
usecase "Trocar Moedas por Vantagem" as CA4
usecase "Cadastrar Vantagem" as CA5
usecase "Enviar Cupom" as CA6
usecase "Enviar Email" as CA9
usecase "Acessar Sistema" as CA11

Aluno --> CA11
Professor --> CA11
EmpresaParceira --> CA11

Aluno --> CA1
Aluno --> CA3
Aluno --> CA4

Professor --> CA2
Professor --> CA3

EmpresaParceira --> CA1
EmpresaParceira --> CA5

CA2 <-- CA9: <<include>>
CA4 <-- CA6: <<include>>
@enduml
