@startuml
node "Servidor React" {
    [FrontEnd: 3000] as FrontEnd
}

node "Servidor de Aplicação" {
    [BackEnd: 8080] as BackEnd
    component [BackEnd] {
        [Cadastrar no Sistema]
        [Distribuir Moedas]
        [Consultar extrato]
        [Trocar Moedas por Vantagem]
        [Cadastrar Vantagem]
        [Enviar Email]
        [Acessar Sistema]
    }
}

database "Banco de Dados" {
    [PostgreSQL: 5432] as PostgreSQL
}

node "Cliente" {
    [navegador]
}

[Cliente] --> [FrontEnd] : HTTP (callbakcs)
[Cliente] --> [BackEnd] : HTTP (REST API)
[BackEnd] --> [PostgreSQL] : <<TCP/IP>>

@enduml
