@startuml
actor Aluno
actor Professor
actor EmpresaParceira

participant FrontEnd
participant BackEnd
database PostgreSQL as BD


== Cadastrar Vantagem (pela Empresa)==
EmpresaParceira -> FrontEnd: Acessar Tela de Cadastro de Vantagem
FrontEnd -> BackEnd: Enviar Dados da Vantagem
BackEnd -> BD: Inserir Vantagem no Banco
BD --> BackEnd: Confirmação de Cadastro
BackEnd --> FrontEnd: Cadastro de Vantagem Confirmado
FrontEnd -> EmpresaParceira: Vantagem Cadastrada

== Listagem de Vantagens (para Aluno) ==
Aluno -> FrontEnd: Acessar Tela de Listagem de Vantagens
FrontEnd -> BackEnd: Solicitar os Dados das Vantagens
BackEnd -> BD: Pegar os dados das Vantagens no Banco
BD --> BackEnd: Enviar os dados das Vantagens existentes
BackEnd --> FrontEnd: Receber os dados das Vantagens
FrontEnd -> Aluno: Listar as Vantagens na tela

== Troca de Moedas por Vantagem (pelo Aluno) ==
Aluno -> FrontEnd: Solicitar Troca por Vantagem
FrontEnd -> BackEnd: Requisição de Troca
BackEnd -> BD: Validar Saldo e Registrar Vantagem
BD --> BackEnd: Confirmação de Vantagem
BackEnd --> FrontEnd: Confirmação de Troca
FrontEnd -> Aluno: Troca Confirmada

@enduml
