@startuml
actor Aluno
actor Professor
actor EmpresaParceira

participant Components
participant Pages
participant Controller
participant Service
participant Repository
database PostgreSQL as BD


== Cadastrar Vantagem (pela Empresa) ==
EmpresaParceira -> Components: Acessar Tela de Cadastro de Vantagem
Components -> Pages: Acessar Tela de Cadastro de Vantagem
Pages -> Controller: Enviar Dados da Vantagem
Controller -> Service: Enviar Dados da Vantagem
Service -> Repository: Enviar Dados da Vantagem
Repository -> BD: Inserir Vantagem no Banco
BD --> Repository: Confirmação de Cadastro
Repository --> Service: Confirmação de Cadastro
Service --> Controller: Confirmação de Cadastro
Controller --> Pages: Cadastro de Vantagem Confirmado
Pages --> Components: Cadastro de Vantagem Confirmado
Components -> EmpresaParceira: Vantagem Cadastrada

== Listagem de Vantagens (para Aluno) ==
Aluno -> Components:  Acessar Tela de Listagem de Vantagens
Components -> Pages:  Acessar Tela de Listagem de Vantagens
Pages -> Controller: Solicitar os Dados das Vantagens
Controller -> Service: Solicitar os Dados das Vantagens
Service -> Repository: Solicitar os Dados das Vantagens
Repository -> BD: Pegar os dados das Vantagens no Banco
BD --> Repository: Enviar os dados das Vantagens existentes
Repository --> Service: Receber os dados das Vantagens
Service --> Controller: Receber os dados das Vantagens
Controller --> Pages: Listar as Vantagens na tela
Pages --> Components:  Listar as Vantagens na tela
Components -> Aluno: Ver as Vantagens Cadastradas

== Troca de Moedas por Vantagem (pelo Aluno) ==
Aluno -> Components:  Acessar Tela de Listagem de Vantagens e clickar em 'Obter'
Components -> Pages:  Acessar Tela de Listagem de Vantagens e clickar em 'Obter'
Pages -> Controller: Enviar os dados da Vantagem e do aluno
Controller -> Service: Enviar os dados da Vantagem e do aluno
Service -> Repository: Enviar os dados da Vantagem e do aluno
Repository -> BD: Verifica se o aluno tem saldo suficiente
BD --> Repository: Confirmação de saldo suficiente
Repository -> BD: Salvar vantagem escolhida (create do histórico) e atualizar saldo do aluno
BD --> Repository: Confirmação de vantagem obtida
Repository --> Service: Confirmação de vantagem obtida
Service --> Controller: Confirmação de vantagem obtida
Controller --> Pages: Confirmação de vantagem obtida
Pages --> Components:  Confirmação de vantagem obtida
Components -> Aluno: Ver a confirmação de vantagem obtida

@enduml
