@startuml
package "Sistema de Moeda Esdutantil" {

    [Navegador] <.. [API]

    [API] -(0- [Cadastrar no Sistema]
    [API] -(0- [Distribuir Moedas]
    [API] -(0- [Consultar extrato]
    [API] -(0- [Trocar Moedas por Vantagem]
    [API] -(0- [Cadastrar Vantagem]
    [API] -(0- [Receber Email]
    [API] -(0- [Resgatar Vantagem]
    [API] -(0- [Acessar Sistema]

    [Cadastrar no Sistema] -(0- [PostgreSQL]:<<TCP/IP>>
    [Distribuir Moedas] -(0- [PostgreSQL]:<<TCP/IP>>
    [Consultar extrato] -(0- [PostgreSQL]:<<TCP/IP>>
    [Trocar Moedas por Vantagem] -(0- [PostgreSQL]:<<TCP/IP>>
    [Cadastrar Vantagem] -(0- [PostgreSQL]:<<TCP/IP>>
    [Receber Email] -(0- [PostgreSQL]:<<TCP/IP>>
    [Resgatar Vantagem] -(0- [PostgreSQL]:<<TCP/IP>>
    [Acessar Sistema] -(0- [PostgreSQL]:<<TCP/IP>>

    [Aluno] <.. [Navegador]
    [Professor] <.. [Navegador]
    [EmpresaParceira] <.. [Navegador]
}

@enduml
