@startuml
package "Sistema de Moeda Esdutantil" {

    [Aluno]
    [Professor]
    [EmpresaParceira]
    [FrontEnd]
    [PostgreSQL]

    component [BackEnd] {
        [Cadastrar no Sistema]
        [Distribuir Moedas]
        [Consultar extrato]
        [Trocar Moedas por Vantagem]
        [Cadastrar Vantagem]
        [Receber Email]
        [Resgatar Vantagem]
        [Acessar Sistema]
    }

    [FrontEnd] -(0- [Cadastrar no Sistema]
    [FrontEnd] -(0- [Distribuir Moedas]
    [FrontEnd] -(0- [Consultar extrato]
    [FrontEnd] -(0- [Trocar Moedas por Vantagem]
    [FrontEnd] -(0- [Cadastrar Vantagem]
    [FrontEnd] -(0- [Receber Email]
    [FrontEnd] -(0- [Resgatar Vantagem]
    [FrontEnd] -(0- [Acessar Sistema]

    [BackEnd] --> [PostgreSQL]:<<TCP/IP>>

    [Aluno] <.. [FrontEnd]
    [Professor] <.. [FrontEnd]
    [EmpresaParceira] <.. [FrontEnd]
}

@enduml
